### ISSUE TITLE
注册登录-提示信息显示调整

### ISSUE THREAD

**Issue by CalebPoon** [AwesomeTickets/Tickets-Client#48]
description 的值根据请求返回的异常码决定。

可能出现的异常码：100,101,102,202,400,401,402

100  请输入11位有效手机号码！
101  短信验证码发送失败，间隔60秒！
102  短信验证码错误！
202  用户不存在，请注册！
400  请设置6位以上数字与字母组合！
401  手机号已注册，请登录！
402  密码错误！

![issue_1](https://user-images.githubusercontent.com/26643585/27508539-fb4b79d4-5919-11e7-870e-ad4b4996d529.png)

**Comment by chynl** [comment]
此 issue 跟 #50 一起修复
