### ISSUE TITLE
购票历史-记录顺序调整

### ISSUE THREAD

**Issue by CalebPoon** [AwesomeTickets/Tickets-Client#52]
历史记录顺序要和接口返回的顺序一致。

**Comment by chynl** [comment]
[获取购票历史](https://github.com/AwesomeTickets/Dashboard/blob/master/doc/api.md#获取购票历史)接口返回的购票历史数据已经是按购票时间排序好的，显示的时候应该按照此顺序来显示，现在的问题是每次刷新页面，购票历史的顺序都会改变。
