### ISSUE TITLE
获取电子票 -增加弹窗信息提示

### ISSUE THREAD

**Issue by CalebPoon** [AwesomeTickets/Tickets-Client#54]
点击「获取电子票」，若座位已被预订，弹窗提示错误信息「晚了一步，您挑的座位已被预定了」按钮「重新选座」，采用此样式：

<img width="460" alt="4a9b327b-b048-444c-b939-0f4aa840e33a" src="https://user-images.githubusercontent.com/26643585/27508668-c6e6abb6-591c-11e7-9ca1-9ccb6bf92e35.png">

**Comment by chynl** [comment]
点击「获取电子票」时很可能该座位正好被别人买走，此时服务器会返回座位已经被购买的错误码，因此需要这个错误提示。

**Comment by saltedFish62** [comment]
哦
